# Игровые объекты
all_sprites = None
player_group = None
evil_group = None
objects = None
pressed = None
player = None
camera = None
inventory = None
clock = None
running = None
music = True
sound = False
sound_run = False
